application: app-name
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: assets/img/favicon.ico
  upload: assets/img/favicon\.ico

- url: /assets
  static_dir: assets

- url: .*
  script: app.py
